version: '3.8'


x-env: &env
  SMS_RATE_LIMIT: 3
  EMAIL_RATE_LIMIT: 3
  RATE_LIMIT_WINDOW_MS: 10000

services:
  user-notifications-manager:
    build:
      context: ./Manager
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      <<: *env
      NOTIFICATION_SERVICE_URL: 'http://notification-service:5001'
    depends_on:
      - notification-service # should wait

  notification-service:
    image: aryekog/backend-interview-notifications-service:0.0.2
    ports:
      - "5001:5001"
    environment:
      <<: *env
      ERROR_RATE: 0 
